spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/boot
    username: postgres
    password: altynbek695
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 9090



